# Generated by Django 5.2.4 on 2025-07-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
                ('index', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField()),
            ],
        ),
    ]
